// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using assassingames_backend.DbContexts;

namespace assassingames_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211105230646_AddParticipation")]
    partial class AddParticipation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("assassingames_backend.Models.Leadership", b =>
                {
                    b.Property<byte[]>("LeadershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("LeadershipEnd")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LeadershipStart")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("OrganiserId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("LeadershipId");

                    b.HasIndex("OrganiserId");

                    b.HasIndex("UserId");

                    b.ToTable("Leaderships");
                });

            modelBuilder.Entity("assassingames_backend.Models.Organiser", b =>
                {
                    b.Property<byte[]>("OrganiserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("County")
                        .HasColumnType("text");

                    b.Property<string>("Municipality")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("OrganiserId");

                    b.ToTable("Organisers");
                });

            modelBuilder.Entity("assassingames_backend.Models.Participation", b =>
                {
                    b.Property<byte[]>("ParticipationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<string>("Campus")
                        .HasColumnType("text");

                    b.Property<string>("HangoutSpots")
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<byte[]>("SeasonId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Stores")
                        .HasColumnType("text");

                    b.Property<string>("Study")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ParticipationId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("UserId");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("assassingames_backend.Models.Season", b =>
                {
                    b.Property<byte[]>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("OrganiserId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegistrationEnd")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("RegistrationStart")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("SeasonEnd")
                        .HasColumnType("datetime");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SeasonStart")
                        .HasColumnType("datetime");

                    b.HasKey("SeasonId");

                    b.HasIndex("OrganiserId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("assassingames_backend.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("assassingames_backend.Models.Leadership", b =>
                {
                    b.HasOne("assassingames_backend.Models.Organiser", "Organiser")
                        .WithMany("Leaderships")
                        .HasForeignKey("OrganiserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("assassingames_backend.Models.User", "User")
                        .WithMany("Leaderships")
                        .HasForeignKey("UserId");

                    b.Navigation("Organiser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("assassingames_backend.Models.Participation", b =>
                {
                    b.HasOne("assassingames_backend.Models.Season", "Season")
                        .WithMany("Participations")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("assassingames_backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("assassingames_backend.Models.Season", b =>
                {
                    b.HasOne("assassingames_backend.Models.Organiser", "Organiser")
                        .WithMany("Seasons")
                        .HasForeignKey("OrganiserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organiser");
                });

            modelBuilder.Entity("assassingames_backend.Models.Organiser", b =>
                {
                    b.Navigation("Leaderships");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("assassingames_backend.Models.Season", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("assassingames_backend.Models.User", b =>
                {
                    b.Navigation("Leaderships");
                });
#pragma warning restore 612, 618
        }
    }
}
