// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using assassingames_backend.DbContexts;

namespace assassingames_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211105195423_AddOrganiserAndSeason")]
    partial class AddOrganiserAndSeason
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("assassingames_backend.Models.Organiser", b =>
                {
                    b.Property<byte[]>("OrganiserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("County")
                        .HasColumnType("text");

                    b.Property<string>("Municipality")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("OrganiserId");

                    b.ToTable("Organisers");
                });

            modelBuilder.Entity("assassingames_backend.Models.Season", b =>
                {
                    b.Property<byte[]>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("OrganiserId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationEnd")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("RegistrationStart")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("SeasonEnd")
                        .HasColumnType("datetime");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("SeasonStart")
                        .HasColumnType("datetime");

                    b.HasKey("SeasonId");

                    b.HasIndex("OrganiserId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("assassingames_backend.Models.Season", b =>
                {
                    b.HasOne("assassingames_backend.Models.Organiser", "Organiser")
                        .WithMany("Seasons")
                        .HasForeignKey("OrganiserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organiser");
                });

            modelBuilder.Entity("assassingames_backend.Models.Organiser", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
